Repository JNU-econovation/Lean-BE, pull requests merged in 2025-01, with the labels that each got.

#4 [FEAT] Users CRUD 구현
  src/main/java/com/duriyou/lean/domain/users/Users.java
  src/main/java/com/duriyou/lean/domain/users/UsersRepository.java
  src/main/java/com/duriyou/lean/service/users/UsersService.java
  src/main/java/com/duriyou/lean/web/UserApiController.java
  src/main/java/com/duriyou/lean/web/dto/UsersResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/UsersSaveRequestDto.java
  src/main/java/com/duriyou/lean/web/dto/UsersUpdateRequestDto.java
Labels: ✨ Feature

#6 Feat/colleges/003
  .idea/.name
  .idea/gradle.xml
  src/main/java/com/duriyou/lean/domain/colleges/Colleges.java
  src/main/java/com/duriyou/lean/domain/colleges/CollegesRepository.java
  src/main/java/com/duriyou/lean/domain/users/Users.java
  src/main/java/com/duriyou/lean/service/colleges/CollegesService.java
  src/main/java/com/duriyou/lean/web/CollegeApiController.java
  src/main/java/com/duriyou/lean/web/dto/Colleges/AllCollegesResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/Colleges/CollegesResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/Colleges/CollegesSaveRequestDto.java
  src/main/java/com/duriyou/lean/web/dto/Colleges/CollegesUpdateRequestDto.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersSaveRequestDto.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersUpdateRequestDto.java
Labels: ✨ Feature

#8 [FEAT] Users 초기값 추가 #7
  src/main/java/com/duriyou/lean/domain/users/Users.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersResponseDto.java
Labels: ✨ Feature

#10 [REFACTOR] Dto 하위 디렉토리 추가 #9
  src/main/java/com/duriyou/lean/service/users/UsersService.java
  src/main/java/com/duriyou/lean/web/UserApiController.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersSaveRequestDto.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersUpdateRequestDto.java
Labels: 🔨 Refactor

#11 [FEAT] 모든 유저 조회 API 추가 #5
  src/main/java/com/duriyou/lean/service/users/UsersService.java
  src/main/java/com/duriyou/lean/web/UserApiController.java
  src/main/java/com/duriyou/lean/web/dto/Users/AllUsersResponseDto.java
Labels: ✨ Feature

#13 [FEAT] Student-Council CRUD 구현 #12
  src/main/java/com/duriyou/lean/domain/student/council/StudentCouncil.java
  src/main/java/com/duriyou/lean/domain/student/council/StudentCouncilRepository.java
  src/main/java/com/duriyou/lean/service/student/council/StudentCouncilService.java
  src/main/java/com/duriyou/lean/web/StudentCouncilApiController.java
  src/main/java/com/duriyou/lean/web/dto/Student/Council/AllStudentCouncilResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/Student/Council/StudentCouncilResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/Student/Council/StudentCouncilSaveRequestDto.java
  src/main/java/com/duriyou/lean/web/dto/Student/Council/StudentCouncilUpdateRequestDto.java
Labels: ✨ Feature

#15 [REFACTOR] Colleges, Users 코드 통일성 작업 #14
  src/main/java/com/duriyou/lean/service/colleges/CollegesService.java
  src/main/java/com/duriyou/lean/service/users/UsersService.java
  src/main/java/com/duriyou/lean/web/CollegeApiController.java
  src/main/java/com/duriyou/lean/web/dto/Colleges/AllCollegesResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersSaveRequestDto.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersUpdateRequestDto.java
Labels: 🔨 Refactor

#17 [FEAT] 학생회 승격 로직 추가 #16
  src/main/java/com/duriyou/lean/domain/users/Users.java
  src/main/java/com/duriyou/lean/service/users/UsersService.java
  src/main/java/com/duriyou/lean/web/UserApiController.java
Labels: ✨ Feature

#20 [FEAT] Users 비밀번호 추가 #19
  build.gradle
  src/main/java/com/duriyou/lean/domain/users/Users.java
  src/main/java/com/duriyou/lean/security/SecurityConfig.java
  src/main/java/com/duriyou/lean/service/users/UsersService.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersSaveRequestDto.java
Labels: ✨ Feature

#21 [FEAT] 로그인 API 구현 #18
  src/main/java/com/duriyou/lean/domain/users/UsersRepository.java
  src/main/java/com/duriyou/lean/service/users/UsersService.java
  src/main/java/com/duriyou/lean/web/UserApiController.java
  src/main/java/com/duriyou/lean/web/dto/Users/SigninRequestDto.java
Labels: ✨ Feature

#23 [REFACTOR] 엔티티 중복 제약 추가 #22
  src/main/java/com/duriyou/lean/domain/colleges/Colleges.java
  src/main/java/com/duriyou/lean/domain/student/council/StudentCouncil.java
  src/main/java/com/duriyou/lean/domain/users/Users.java
Labels: 🔨 Refactor

#26 [FEAT] ItemsAPI 개발
  .idea/dataSources.xml
  src/main/java/com/duriyou/lean/domain/dates/RentalDates.java
  src/main/java/com/duriyou/lean/domain/dates/RentalDatesRepository.java
  src/main/java/com/duriyou/lean/domain/dates/ReservationDates.java
  src/main/java/com/duriyou/lean/domain/dates/ReservationDatesRepository.java
  src/main/java/com/duriyou/lean/domain/dates/ReturnDates.java
  src/main/java/com/duriyou/lean/domain/dates/ReturnDatesRepository.java
  src/main/java/com/duriyou/lean/domain/items/ItemAmounts.java
  src/main/java/com/duriyou/lean/domain/items/ItemAmountsRepository.java
  src/main/java/com/duriyou/lean/domain/items/Items.java
  src/main/java/com/duriyou/lean/domain/items/ItemsRepository.java
  src/main/java/com/duriyou/lean/domain/rentals/Rentals.java
  src/main/java/com/duriyou/lean/domain/rentals/RentalsRepository.java
  src/main/java/com/duriyou/lean/domain/student/council/StudentCouncil.java
  src/main/java/com/duriyou/lean/service/items/ItemsService.java
  src/main/java/com/duriyou/lean/service/rentals/RentalsService.java
  src/main/java/com/duriyou/lean/web/ItemsApiController.java
  src/main/java/com/duriyou/lean/web/RentalsApiController.java
  src/main/java/com/duriyou/lean/web/dto/items/ItemAmountsResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/items/ItemAmountsSaveRequestDto.java
  src/main/java/com/duriyou/lean/web/dto/items/ItemAmountsUpdateRequestDto.java
  src/main/java/com/duriyou/lean/web/dto/items/ItemsNameResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/items/ItemsResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/items/ItemsSaveRequestDto.java
  src/main/java/com/duriyou/lean/web/dto/rentals/RentalsResponseDto.java
  src/test/java/ItemsServiceTest.java
Labels: ✨ Feature

#27 [FEAT] RentalsAPI 개발
  build.gradle
  src/main/java/com/duriyou/lean/domain/dates/RentalDates.java
  src/main/java/com/duriyou/lean/domain/dates/ReservationDates.java
  src/main/java/com/duriyou/lean/domain/dates/ReturnDates.java
  src/main/java/com/duriyou/lean/domain/items/Items.java
  src/main/java/com/duriyou/lean/domain/rentals/Rentals.java
  src/main/java/com/duriyou/lean/domain/rentals/RentalsRepository.java
  src/main/java/com/duriyou/lean/domain/student/council/StudentCouncilRepository.java
  src/main/java/com/duriyou/lean/domain/users/UsersRepository.java
  src/main/java/com/duriyou/lean/service/rentals/RentalsService.java
  src/main/java/com/duriyou/lean/web/RentalsApiController.java
  src/main/java/com/duriyou/lean/web/dto/rentals/RentalDetailsDto.java
  src/main/java/com/duriyou/lean/web/dto/rentals/RentalDetailsResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/rentals/RentalsResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/rentals/StudentCouncilAllRentalsDto.java
  src/main/java/com/duriyou/lean/web/dto/rentals/StudentCouncilAllRentalsResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/rentals/UserAllRentalsDto.java
  src/main/java/com/duriyou/lean/web/dto/rentals/UserAllRentalsResponseDto.java
  src/main/resources/application.yml
Labels: ✨ Feature

#29 [FIX] spring security cors 오류 해결 #28
  src/main/java/com/duriyou/lean/security/SecurityConfig.java
Labels: 🐞 BugFix

#30 Fix : Signin Response 값 수정
  src/main/java/com/duriyou/lean/service/users/UsersService.java
  src/main/java/com/duriyou/lean/web/UserApiController.java
Labels: 🐞 BugFix

#33 [FEAT] userResponseDto값을 받아 올 때 studentcouncil_id도 가져올 수 있게 수정
  src/main/java/com/duriyou/lean/domain/student/council/StudentCouncil.java
  src/main/java/com/duriyou/lean/domain/users/Users.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersResponseDto.java
Labels: ✨ Feature

#35 [FIX] user_id로 데이터 불러올때 isStudentCouncil 값 불러오도록 수정 #34
  src/main/java/com/duriyou/lean/domain/users/Users.java
  src/main/java/com/duriyou/lean/service/users/UsersService.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/Users/UsersUpdateRequestDto.java
Labels: 🐞 BugFix

#37 [FIX] 학생회 리스트 불러올때 college name도 출력하도록 수정 #36
  src/main/java/com/duriyou/lean/web/dto/Student/Council/AllStudentCouncilResponseDto.java
Labels: 🐞 BugFix

#44 [FEAT] User Response에 StudentCouncilId 값 추가
  src/main/java/com/duriyou/lean/web/dto/Users/UsersResponseDto.java
Labels: ✨ Feature

#46 [FEAT] 세부정보확인Api에서 ResponseDto 필드 추가
  src/main/java/com/duriyou/lean/domain/rentals/RentalsRepository.java
  src/main/java/com/duriyou/lean/service/rentals/RentalsService.java
  src/main/java/com/duriyou/lean/web/dto/rentals/RentalDetailsDto.java
  src/main/java/com/duriyou/lean/web/dto/rentals/RentalDetailsResponseDto.java
Labels: ✨ Feature

#48 [FEAT] 예약시 사용자로부터 현재 날짜 입력받는 Response Dto 및 서비스 로직 개발
  src/main/java/com/duriyou/lean/service/rentals/RentalsService.java
  src/main/java/com/duriyou/lean/web/RentalsApiController.java
  src/main/java/com/duriyou/lean/web/dto/rentals/ReservationRequestDto.java
Labels: ✨ Feature

#51 BugFix: api/v1/rentals/details/{rental_id} api 에서 response body 중 rental_status 추가
  src/main/java/com/duriyou/lean/domain/rentals/RentalsRepository.java
  src/main/java/com/duriyou/lean/service/rentals/RentalsService.java
  src/main/java/com/duriyou/lean/web/dto/rentals/RentalDetailsDto.java
  src/main/java/com/duriyou/lean/web/dto/rentals/RentalDetailsResponseDto.java
Labels: ✨ Feature

#53 [FEAT] 학생회에서 모든 정보 불러올 때 rentalExpirationDate 추가
  src/main/java/com/duriyou/lean/domain/student/council/StudentCouncilRepository.java
  src/main/java/com/duriyou/lean/service/rentals/RentalsService.java
  src/main/java/com/duriyou/lean/web/dto/Student/Council/AllStudentCouncilResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/Student/Council/StudentCouncilResponseDto.java
  src/main/java/com/duriyou/lean/web/dto/rentals/StudentCouncilAllRentalsDto.java
  src/main/java/com/duriyou/lean/web/dto/rentals/StudentCouncilAllRentalsResponseDto.java
Labels: ✨ Feature

#55 BugFix: 대기중인 상태에서 expiration rental date가 null값으로 return이 안되는 문제
  src/main/java/com/duriyou/lean/domain/student/council/StudentCouncilRepository.java
Labels: 🐞 BugFix

#57 ItemsStudentCouncilResponseDto에 collegeName필드 추가
  src/main/java/com/duriyou/lean/web/dto/items/ItemsStudentCouncilResponseDto.java
Labels: 🐞 BugFix

#58 [BugFix] 학생회가 물품의 총량을 조회하는 로직 수정
  src/main/java/com/duriyou/lean/service/items/ItemsService.java
  src/main/java/com/duriyou/lean/web/dto/items/ItemAmountsResponseDto.java
Labels: 🐞 BugFix

#60 [FIX] RentalDetail Response에 useDepartment 추가 #59
  src/main/java/com/duriyou/lean/domain/rentals/RentalsRepository.java
  src/main/java/com/duriyou/lean/service/rentals/RentalsService.java
  src/main/java/com/duriyou/lean/web/dto/rentals/RentalDetailsDto.java
  src/main/java/com/duriyou/lean/web/dto/rentals/RentalDetailsResponseDto.java
Labels: 🐞 BugFix

#62 [FEAT] JWT 토큰 인증방식 구현 #61
  build.gradle
  src/main/java/com/duriyou/lean/security/JwtTokenProvider.java
  src/main/java/com/duriyou/lean/security/SecurityConfig.java
  src/main/java/com/duriyou/lean/service/users/UsersService.java
  src/main/java/com/duriyou/lean/web/UserApiController.java
  src/main/java/com/duriyou/lean/web/dto/token/TokenResponseDto.java
  src/main/resources/application.yml
Labels: ✨ Feature

#63 [FIX] access token 만료시간 변경 #61
  src/main/resources/application.yml
Labels: 🐞 BugFix
